 node.name: ServerHostname
 config.reload.automatic: true
 config.reload.interval: 5s
 http.host: "ServerIPv4Address"
 http.port: 9600
# path.data: "c:/ElasticStack/Data/Logstash"
# path.logs: "c:/ElasticStack/Logs/Logstash"
# log.level: trace
# Uncomment and configure below for x-pack integration
# xpack.monitoring.elasticsearch.username: logstash_system
# xpack.monitoring.elasticsearch.password: logstash